### ISSUE TITLE
Adjusting dimensions for Line Chart

### ISSUE THREAD

**Issue by justuswilhelm** [simonh1000/elm-charts#1]
I am really happy to have found a working and easy to use charting library for Elm. Now, I was wondering whether there was an easy way to adjust the dimension for line charts created using the `lChart` function. I see that the 400x300 dimensions are hard coded right now.

If you could give me a pointer on what the best way to have dimensions adjustable is, I will gladly write the patch myself and open a PR.

Many thanks for you work!

**Comment by simonh1000** [comment]
Thanks for the question. It does make sense to add the dimensions to the model, and perhaps the line width, and I should have used the first color in the list rather than hard coding that too. Feel free to add dimensions - as a simple record I think - to the model and a function 

`dimensions : Int -> Int -> Model -> Model`

to set them (I'm avoiding an init function with hundreds of variables), and then they can be used in the chartView

Happy to accept a PR! :-)

**Comment by simonh1000** [comment]
Added in 3.1.0.
